const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const names={dashboard:'Dashboard',calculator:'Calculator',smart:'Smart Calculator',scientific:'Scientific',finance:'Finance Tools',converter:'Converters',math:'Math Tools',stats:'Statistics',date:'Date & Time',history:'History',favorites:'Favorites',settings:'Settings',about:'About'};
let history=JSON.parse(localStorage.getItem('history')||'[]'),precision=Number(localStorage.getItem('precision')||8),memory=0,expr='',sciMode='sqrt',favorites=JSON.parse(localStorage.getItem('favorites')||'[]');
function save(k,v){localStorage.setItem(k,v)} function fmt(n){if(!Number.isFinite(n))return'Error';return Number(n.toPrecision(precision)).toString()}
function show(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if($('#title'))$('#title').textContent=names[id]||id;if($('#sidebar'))$('#sidebar').classList.remove('open');if(id==='history')renderHistory();if(id==='favorites')renderFavorites()}
$$('.nav').forEach(x=>x.onclick=()=>show(x.dataset.page)); if($('#menu'))$('#menu').onclick=()=>$('#sidebar').classList.toggle('open');
if($('#theme'))$('#theme').onclick=()=>{document.body.classList.toggle('light');save('theme',document.body.classList.contains('light')?'light':'dark');if($('#themeSelect'))$('#themeSelect').value=document.body.classList.contains('light')?'light':'dark'};
if(localStorage.getItem('theme')==='light')document.body.classList.add('light'); if(localStorage.getItem('accent'))document.body.classList.add(localStorage.getItem('accent'));
const tools=[['＋','Basic Calculator','Arithmetic, memory and keyboard.','calculator'],['🧠','Smart Calculator','Natural phrases and quick math.','smart'],['∑','Scientific','Trig, logs, powers and factorial.','scientific'],['₹','Finance','EMI, SIP, GST and more.','finance'],['⇄','Converters','Units for everyday calculations.','converter'],['√','Math Tools','Fractions, matrices and number theory.','math'],['📊','Statistics','Mean, median, mode and deviation.','stats'],['◷','Date & Time','Age, difference, countdown and stopwatch.','date']];
function renderTools(){if(!$('#quickTools'))return;$('#quickTools').innerHTML=tools.map(t=>`<article class="tool-card" onclick="show('${t[3]}')"><span class="fav-star" title="Favorite" onclick="event.stopPropagation();toggleFavorite('${t[3]}')">${favorites.includes(t[3])?'★':'☆'}</span><div class="ico">${t[0]}</div><h3>${t[1]}</h3><p>${t[2]}</p><b>Open tool →</b></article>`).join('')}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save('favorites',JSON.stringify(favorites));renderTools();renderFavorites();toast(favorites.includes(id)?'Added to favorites':'Removed from favorites')}
function renderFavorites(){if(!$('#favoriteList'))return;let a=tools.filter(t=>favorites.includes(t[3]));$('#favoriteList').innerHTML=a.length?a.map(t=>`<article class="tool-card" onclick="show('${t[3]}')"><span class="fav-star">★</span><div class="ico">${t[0]}</div><h3>${t[1]}</h3><p>${t[2]}</p><b>Open tool →</b></article>`).join(''):'<div class="panel"><p class="hint">No favorites yet. Star a tool on the dashboard.</p></div>'}
renderTools();renderFavorites();
function evaluate(s){if(!s||!/^[0-9+\-*/().%\s]+$/.test(s))throw Error('Invalid');s=s.replace(/(\d+(?:\.\d+)?)%/g,'($1/100)');return Function('"use strict";return ('+s+')')()}
function addHist(e,r){history.unshift({e,r,t:new Date().toLocaleString()});history=history.slice(0,200);save('history',JSON.stringify(history));renderMini()}
function calc(){if(!expr)return;try{let r=fmt(evaluate(expr));$('#calcExpr').textContent=expr;$('#calcOut').textContent=r;addHist(expr,r)}catch(e){$('#calcOut').textContent='Error';toast('Invalid expression')}}
$$('.keys button').forEach(b=>b.onclick=()=>{let v=b.dataset.v,a=b.dataset.a;if(a==='clear'){expr='';$('#calcExpr').textContent='';$('#calcOut').textContent='0';return}if(a==='back'){expr=expr.slice(0,-1);$('#calcExpr').textContent=expr;return}if(a==='equal'){calc();return}if(v){expr+=v;$('#calcExpr').textContent=expr}});
document.addEventListener('keydown',e=>{if(!$('#calculator')?.classList.contains('active'))return;if(/^[0-9+\-*/().%]$/.test(e.key)){expr+=e.key;$('#calcExpr').textContent=expr}if(e.key==='Enter'){e.preventDefault();calc()}if(e.key==='Backspace'){expr=expr.slice(0,-1);$('#calcExpr').textContent=expr}if(e.key==='Escape'){expr='';$('#calcExpr').textContent='';$('#calcOut').textContent='0'}});
$$('[data-m]').forEach(b=>b.onclick=()=>{let a=b.dataset.m;if(a==='MC')memory=0;if(a==='MR'){expr+=String(memory);$('#calcExpr').textContent=expr}if(a==='M+' )memory+=Number($('#calcOut').textContent)||0;if(a==='M-')memory-=Number($('#calcOut').textContent)||0;toast('Memory '+a)});
function renderMini(){if($('#miniHistory'))$('#miniHistory').innerHTML=history.slice(0,8).map(x=>`<div class="recent-row"><small>${x.t} · ${x.e}</small><b>= ${x.r}</b></div>`).join('')||'<p class="hint">No calculations yet.</p>'}function renderHistory(){if(!$('#historyList'))return;$('#historyList').innerHTML=history.map((x,i)=>`<div class="history-row"><div><small>${x.t}</small><div>${x.e}</div></div><div><b>${x.r}</b><span class="history-actions"><button class="ghost" onclick="copyText('${String(x.r).replace(/'/g,"\\'")}')">Copy</button><button class="ghost" onclick="reuseHist(${i})">Use</button><button class="ghost" onclick="deleteHist(${i})">Delete</button></span></div></div>`).join('')||'<p class="hint">No history.</p>'}
function clearHistory(){history=[];save('history','[]');renderMini();renderHistory();toast('History cleared')}function deleteHist(i){history.splice(i,1);save('history',JSON.stringify(history));renderHistory();renderMini()}function reuseHist(i){expr=history[i].e;show('calculator');$('#calcExpr').textContent=expr;toast('Calculation loaded')}function exportHistory(){let blob=new Blob([history.map(x=>`${x.t} | ${x.e} = ${x.r}`).join('\n')],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='adarsh-calculator-history.txt';a.click();URL.revokeObjectURL(a.href)}
function copyText(t){navigator.clipboard?.writeText(t).then(()=>toast('Copied')).catch(()=>toast(t))}
function smartExample(x){$('#smartInput').value=x;smartCalc()}function smartCalc(){let s=$('#smartInput').value.trim().toLowerCase(),r;if(!s)return;try{let m=s.match(/^([\d.]+)%\s+of\s+([\d.]+)$/);if(m)r=+m[1]*+m[2]/100;else if((m=s.match(/^([\d.]+)%\s+discount\s+on\s+([\d.]+)$/)))r=+m[2]*(1-+m[1]/100);else if((m=s.match(/^sqrt\s+([\d.]+)$/)))r=Math.sqrt(+m[1]);else if((m=s.match(/^([\d.]+)\s*\^\s*([\d.]+)$/)))r=Math.pow(+m[1],+m[2]);else r=evaluate(s.replace(/x/g,'*'));r=fmt(r);$('#smartOut').textContent='Result: '+r;addHist($('#smartInput').value,r)}catch(e){$('#smartOut').textContent='Could not understand that';toast('Try one of the examples')}}
const sci=[['sin','sin'],['cos','cos'],['tan','tan'],['√','sqrt'],['log','log'],['ln','ln'],['x²','square'],['x³','cube'],['π','pi'],['e','e'],['abs','abs'],['n!','fact']];if($('#sciButtons'))$('#sciButtons').innerHTML=sci.map(x=>`<button data-s="${x[1]}">${x[0]}</button>`).join('');$$('[data-s]').forEach(b=>b.onclick=()=>{sciMode=b.dataset.s;$$('[data-s]').forEach(x=>x.style.outline='');b.style.outline='2px solid var(--accent)';if(sciMode==='pi'||sciMode==='e'){let r=sciMode==='pi'?Math.PI:Math.E;$('#sciExpr').textContent=sciMode;$('#sciOut').textContent=fmt(r)}});
$('#sciGo')?.addEventListener('click',()=>{let x=Number($('#sciInput').value),ang=$('#angle').value,rad=ang==='Degrees'?x*Math.PI/180:x,r;switch(sciMode){case'sin':r=Math.sin(rad);break;case'cos':r=Math.cos(rad);break;case'tan':r=Math.tan(rad);break;case'sqrt':r=Math.sqrt(x);break;case'log':r=Math.log10(x);break;case'ln':r=Math.log(x);break;case'square':r=x*x;break;case'cube':r=x*x*x;break;case'abs':r=Math.abs(x);break;case'fact':if(x<0||!Number.isInteger(x)||x>170)r=NaN;else{r=1;for(let i=2;i<=x;i++)r*=i}break;case'pi':r=Math.PI;break;case'e':r=Math.E;break}let z=fmt(r);$('#sciExpr').textContent=`${sciMode}(${x})`;$('#sciOut').textContent=z;addHist(`${sciMode}(${x})`,z)});
function num(id){let e=$(id);return e?Number(e.value)||0:0}function out(id,t){if($(id))$(id).textContent=t}
function simpleInterest(){let p=num('#siP'),r=num('#siR'),t=num('#siT'),i=p*r*t/100;out('#siO',`Interest: ₹${fmt(i)} · Total: ₹${fmt(p+i)}`)}function compoundInterest(){let p=num('#ciP'),r=num('#ciR')/100,t=num('#ciT'),n=num('#ciN')||12,a=p*Math.pow(1+r/n,n*t);out('#ciO',`Amount: ₹${fmt(a)} · Interest: ₹${fmt(a-p)}`)}function emi(){let p=num('#emiP'),r=num('#emiR')/1200,n=num('#emiT')*12,m=r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;out('#emiO',`Monthly EMI: ₹${fmt(m)} · Total: ₹${fmt(m*n)}`)}function gst(){let p=num('#gstP'),r=num('#gstR'),t=p*r/100;out('#gstO',`GST: ₹${fmt(t)} · Total: ₹${fmt(p+t)}`)}function discount(){let p=num('#disP'),r=num('#disR'),d=p*r/100;out('#disO',`Discount: ₹${fmt(d)} · Final: ₹${fmt(p-d)}`)}function profit(){let c=num('#plC'),s=num('#plS'),d=s-c,p=c?Math.abs(d)/c*100:0;out('#plO',c?`${d>=0?'Profit':'Loss'}: ₹${fmt(Math.abs(d))} (${fmt(p)}%)`:'Cost price cannot be 0')}function sip(){let m=num('#sipP'),r=num('#sipR')/1200,n=num('#sipT')*12,a=r?m*(Math.pow(1+r,n)-1)/r*(1+r):m*n;out('#sipO',`Estimated value: ₹${fmt(a)} · Invested: ₹${fmt(m*n)}`)}function percentage(){out('#pctO',fmt(num('#pctA')*num('#pctB')/100))}function taxCalc(){let a=num('#taxP'),r=num('#taxR'),t=a*r/100;out('#taxO',`Tax: ₹${fmt(t)} · Net: ₹${fmt(a-t)}`)}function inflation(){let p=num('#infP'),r=num('#infR')/100,t=num('#infT');out('#infO',`Future equivalent: ₹${fmt(p*Math.pow(1+r,t))}`)}function breakEven(){let f=num('#beF'),p=num('#beP'),v=num('#beV'),q=p>v?f/(p-v):NaN;out('#beO',`Break-even units: ${fmt(q)}`)}
const rates={INR:1,USD:0.0119,EUR:0.0102,GBP:0.0088,JPY:1.75,AED:0.0437};function currencyCalc(){let a=num('#curA'),f=$('#curFrom').value,t=$('#curTo').value;out('#curO',`${fmt(a)} ${f} ≈ ${fmt(a*rates[f]/rates[t])} ${t}`)}
const data={Length:{m:1,cm:.01,km:1000,mi:1609.344,ft:.3048,in:.0254},Weight:{g:1,kg:1000,lb:453.59237,oz:28.3495},Area:{'m²':1,'km²':1e6,'ft²':.092903,acre:4046.856},Speed:{'m/s':1,'km/h':1/3.6,mph:.44704},Volume:{L:1,mL:.001,'m³':1000,gal:3.78541},Time:{sec:1,min:60,hour:3600,day:86400},Data:{B:1,KB:1024,MB:1048576,GB:1073741824,TB:1099511627776},Pressure:{Pa:1,kPa:1000,bar:100000,atm:101325},Energy:{J:1,kJ:1000,cal:4.184,kWh:3600000},Power:{W:1,kW:1000,hp:745.7},Frequency:{Hz:1,kHz:1000,MHz:1e6},Force:{N:1,kN:1000,lbf:4.44822},Torque:{'N·m':1,'kgf·m':9.80665,'lb·ft':1.35582},Fuel:{'km/L':1,'L/100km':1,'mpg':1},Angle:{deg:1,rad:180/Math.PI,grad:.9},Cooking:{tsp:1,tbsp:3,cup:48,ml:.202884}};
function setupConv(){let c=$('#convCat').value,u=c==='Temperature'?['Celsius','Fahrenheit','Kelvin']:Object.keys(data[c]);$('#convFrom').innerHTML=u.map(x=>`<option>${x}</option>`).join('');$('#convTo').innerHTML=u.map(x=>`<option>${x}</option>`).join('');if(u[1])$('#convTo').selectedIndex=1;convert()}function convert(){let c=$('#convCat').value,v=num('#convVal'),f=$('#convFrom').value,t=$('#convTo').value,r;if(c==='Temperature'){let k=f==='Celsius'?v+273.15:f==='Fahrenheit'?(v-32)*5/9+273.15:v;r=t==='Celsius'?k-273.15:t==='Fahrenheit'?(k-273.15)*9/5+32:k}else if(c==='Fuel'){let kmL=f==='L/100km'?100/v:f==='mpg'?v/2.35215:v; r=t==='L/100km'?100/kmL:t==='mpg'?kmL*2.35215:kmL}else r=v*data[c][f]/data[c][t];r=Number(r.toPrecision(precision));$('#convResult').value=r;$('#convText').textContent=`${v} ${f} = ${r} ${t}`}if($('#convCat')){$('#convCat').innerHTML=Object.keys(data).concat('Temperature').map(x=>`<option>${x}</option>`).join('');$('#convCat').onchange=setupConv;$('#convVal').oninput=convert;$('#convFrom').onchange=convert;$('#convTo').onchange=convert;$('#swap').onclick=()=>{let a=$('#convFrom').value,b=$('#convTo').value;$('#convFrom').value=b;$('#convTo').value=a;convert()};setupConv()}
function gcd(a,b){a=Math.abs(Math.trunc(a));b=Math.abs(Math.trunc(b));while(b){[a,b]=[b,a%b]}return a}function hcfLcm(){let a=num('#hA'),b=num('#hB'),g=gcd(a,b),l=a&&b?Math.abs(a*b)/g:0;out('#hO',`HCF: ${g} · LCM: ${l}`)}function average(){let a=$('#avg').value.split(',').map(Number).filter(Number.isFinite);if(!a.length)return out('#avgO','Enter numbers');out('#avgO',`Average: ${fmt(a.reduce((x,y)=>x+y,0)/a.length)}`)}function quadratic(){let a=num('#qa'),b=num('#qb'),c=num('#qc'),d=b*b-4*a*c;if(!a)return out('#qO','a cannot be 0');if(d<0)return out('#qO','No real roots');out('#qO',`x₁ = ${fmt((-b+Math.sqrt(d))/(2*a))} · x₂ = ${fmt((-b-Math.sqrt(d))/(2*a))}`)}function isPrime(){let n=Math.floor(num('#prime'));if(n<2)return out('#primeO',`${n} is not prime`);for(let i=2;i*i<=n;i++)if(n%i===0)return out('#primeO',`${n} is not prime`);out('#primeO',`${n} is prime`)}function parseFrac(s){let a=s.trim().split('/');if(a.length!==2||!Number(a[1]))throw Error();return[Number(a[0]),Number(a[1])]}function fraction(){try{let[a,b]=parseFrac($('#f1').value),[c,d]=parseFrac($('#f2').value),o=$('#fop').value,n=o==='+'?a*d+c*b:o==='−'?a*d-c*b:o==='×'?a*c:a*d,den=o==='+'||o==='−'||o==='×'?b*d:b*c;if(den<0){n=-n;den=-den}let g=gcd(n,den);out('#fO',`${n/g}/${den/g}`)}catch(e){out('#fO','Use format a/b')}}function ratioCalc(){let a=num('#ratioA'),b=num('#ratioB'),g=gcd(a,b);out('#ratioO',g?`${a/g}:${b/g}`:'Invalid ratio')}function fact(n){if(n<0||!Number.isInteger(n)||n>170)throw Error();let x=1;for(let i=2;i<=n;i++)x*=i;return x}function permCalc(){let n=Math.floor(num('#pn')),r=Math.floor(num('#pr'));if(n<0||r<0||r>n)return out('#permO','Need 0 ≤ r ≤ n');let p=fact(n)/fact(n-r),c=p/fact(r);out('#permO',`nPr = ${p} · nCr = ${c}`)}function matrixCalc(){let a=num('#m11'),b=num('#m12'),c=num('#m21'),d=num('#m22');out('#matrixO',`Determinant: ${a*d-b*c} · Trace: ${a+d}`)}
function statsCalc(){let a=$('#statsInput').value.split(',').map(Number).filter(Number.isFinite);if(!a.length)return out('#statsOut','Enter numbers');a.sort((x,y)=>x-y);let mean=a.reduce((x,y)=>x+y,0)/a.length,med=a.length%2?a[(a.length-1)/2]:(a[a.length/2-1]+a[a.length/2])/2,map={};a.forEach(x=>map[x]=(map[x]||0)+1);let mx=Math.max(...Object.values(map)),mode=mx>1?Object.keys(map).filter(k=>map[k]===mx).join(', '):'No mode';let variance=a.reduce((s,x)=>s+(x-mean)**2,0)/a.length;out('#statsOut',`Count: ${a.length} · Mean: ${fmt(mean)} · Median: ${fmt(med)} · Mode: ${mode} · Min: ${a[0]} · Max: ${a[a.length-1]} · Range: ${fmt(a[a.length-1]-a[0])} · Std dev: ${fmt(Math.sqrt(variance))}`)}
function ageCalc(){let d=new Date($('#dob').value),a=new Date($('#asof').value);if(isNaN(d)||isNaN(a))return out('#ageO','Select both dates');let y=a.getFullYear()-d.getFullYear(),m=a.getMonth()-d.getMonth(),days=a.getDate()-d.getDate();if(days<0){m--;days+=new Date(a.getFullYear(),a.getMonth(),0).getDate()}if(m<0){y--;m+=12}out('#ageO',`${y} years, ${m} months, ${days} days`)}function dateDiff(){let a=new Date($('#d1').value),b=new Date($('#d2').value);if(isNaN(a)||isNaN(b))return out('#dateO','Select both dates');let d=Math.abs(Math.round((b-a)/86400000));out('#dateO',`${d} days · ${fmt(d/7)} weeks`)}
let countTimer=null;function startCountdown(){stopCountdown();countTimer=setInterval(()=>{let t=new Date($('#countTarget').value)-Date.now();if(t<=0){$('#countOut').textContent='00d 00h 00m 00s';stopCountdown();toast('Countdown finished');return}let s=Math.floor(t/1000),d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);s%=60;$('#countOut').textContent=`${String(d).padStart(2,'0')}d ${String(h).padStart(2,'0')}h ${String(m).padStart(2,'0')}m ${String(s).padStart(2,'0')}s`},250)}function stopCountdown(){clearInterval(countTimer);countTimer=null}
let swTimer=null,swStart=0,swElapsed=0;function paintSW(){let t=swElapsed+(swTimer?Date.now()-swStart:0),ms=Math.floor(t/100),sec=Math.floor(t/1000)%60,min=Math.floor(t/60000)%60,hr=Math.floor(t/3600000);$('#stopOut').textContent=`${String(hr).padStart(2,'0')}:${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${ms%10}`}function startStopwatch(){if(swTimer)return;swStart=Date.now();swTimer=setInterval(paintSW,100)}function pauseStopwatch(){if(swTimer){swElapsed+=Date.now()-swStart;clearInterval(swTimer);swTimer=null;paintSW()}}function resetStopwatch(){pauseStopwatch();swElapsed=0;paintSW()}
if($('#themeSelect')){$('#themeSelect').value=localStorage.getItem('theme')||'dark';$('#themeSelect').onchange=e=>{document.body.classList.toggle('light',e.target.value==='light');save('theme',e.target.value)}}if($('#precision')){$('#precision').value=precision;$('#precision').onchange=e=>{precision=Number(e.target.value);save('precision',precision)}}if($('#sound')){$('#sound').value=localStorage.getItem('sound')||'off';$('#sound').onchange=e=>save('sound',e.target.value)}if($('#accent')){$('#accent').value=localStorage.getItem('accent')||'violet';$('#accent').onchange=e=>{['violet','blue','green','orange'].forEach(x=>document.body.classList.remove(x));let v=e.target.value;save('accent',v);if(v!=='violet')document.body.classList.add(v)}}
function resetAll(){localStorage.clear();location.reload()}function toast(message){let e=$('#toast');if(!e)return;e.textContent=message;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),1500)}(()=>{const splash=document.getElementById('splash'),pct=document.getElementById('splashPercent'),status=document.getElementById('splashStatus');if(!splash)return;let start=performance.now(),duration=4200;const labels=[[0,'Loading...'],[18,'Preparing tools...'],[42,'Initializing engine...'],[68,'Loading calculator...'],[88,'Finalizing...'],[100,'Ready!']];function tick(t){let p=Math.min(100,Math.round(((t-start)/duration)*100));if(pct)pct.textContent=p+'%';let label=labels.reduce((a,x)=>p>=x[0]?x:a,labels[0]);if(status)status.textContent=label[1];if(p<100)requestAnimationFrame(tick)}requestAnimationFrame(tick);setTimeout(()=>{splash.classList.add('is-hidden')},5900)})();if($('#year'))$('#year').textContent=new Date().getFullYear();renderMini();

/* ===== ADVANCED EXPERIENCE PACK ===== */
let calcUndoStack=[];
function pushUndo(){calcUndoStack.push(expr);if(calcUndoStack.length>40)calcUndoStack.shift()}
function undoCalc(){if(!calcUndoStack.length){toast('Nothing to undo');return}expr=calcUndoStack.pop()||'';$('#calcExpr').textContent=expr;$('#calcOut').textContent=expr?$('#calcOut').textContent:'0';toast('Undone')}
function copyResult(){copyText($('#calcOut')?.textContent||'0')}
function bmiCalc(){let w=num('#bmiW'),h=num('#bmiH')/100;if(w<=0||h<=0)return out('#bmiO','Enter valid weight and height');let b=w/(h*h),cat=b<18.5?'Below reference range':b<25?'Reference range':b<30?'Above reference range':'High reference range';out('#bmiO',`BMI: ${fmt(b)} · ${cat}`)}
function unitPriceCalc(){let p=num('#upPrice'),q=num('#upQty');out('#upO',q>0?`Unit price: ₹${fmt(p/q)}`:'Quantity must be greater than 0')}
function proportionCalc(){let a=num('#propA'),b=num('#propB'),c=num('#propC');out('#propO',b?`D = ${fmt(b*c/a)}`:'B cannot be 0')}
function pctChangeCalc(){let a=num('#pcA'),b=num('#pcB');out('#pcO',a?`${b>=a?'Increase':'Decrease'}: ${fmt(Math.abs((b-a)/a*100))}%`:'Old value cannot be 0')}
function baseCalc(){let n=Number($('#baseN')?.value),base=Number($('#baseTo')?.value);out('#baseO',Number.isInteger(n)&&n>=0?`${n}₁₀ = ${n.toString(base).toUpperCase()}${base===2?'₂':base===8?'₈':'₁₆'}`:'Enter a non-negative integer')}
function fromBaseCalc(){let s=($('#baseInput')?.value||'').trim(),base=Number($('#baseFrom')?.value);if(!s)return out('#fromBaseO','Enter a value');let valid=base===2?/^[01]+$/:base===8?/^[0-7]+$/:/^[0-9a-f]+$/i;if(!valid.test(s))return out('#fromBaseO','Invalid digits for selected base');let n=parseInt(s,base);out('#fromBaseO',`${s.toUpperCase()} = ${n}₁₀`)}
function exportCSV(){let rows=[['Date','Expression','Result'],...history.map(x=>[x.t,x.e,x.r])];let csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='free-study-calculator-history.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('CSV exported')}
function applyTheme(v){document.body.classList.remove('light');if(v==='light')document.body.classList.add('light');if(v==='auto'&&window.matchMedia('(prefers-color-scheme:light)').matches)document.body.classList.add('light');save('theme',v);if($('#themeSelect'))$('#themeSelect').value=v}
if($('#themeSelect'))$('#themeSelect').onchange=e=>applyTheme(e.target.value);
applyTheme(localStorage.getItem('theme')||'dark');
window.matchMedia?.('(prefers-color-scheme:light)').addEventListener?.('change',()=>{if(localStorage.getItem('theme')==='auto')applyTheme('auto')});
if($('#historySearch'))$('#historySearch').addEventListener('input',()=>renderHistory());
const _renderHistory=renderHistory;
renderHistory=function(){if(!$('#historyList'))return;let q=($('#historySearch')?.value||'').toLowerCase().trim();let list=history.filter(x=>!q||`${x.t} ${x.e} ${x.r}`.toLowerCase().includes(q));if($('#historyCount'))$('#historyCount').textContent=`${list.length} calculation${list.length===1?'':'s'}`;$('#historyList').innerHTML=list.map((x)=>{let i=history.indexOf(x);return `<div class="history-row"><div><small>${x.t}</small><div>${x.e}</div></div><div><b>${x.r}</b><span class="history-actions"><button class="ghost" onclick="copyText('${String(x.r).replace(/'/g,"\\'")}')">Copy</button><button class="ghost" onclick="reuseHist(${i})">Use</button><button class="ghost" onclick="deleteHist(${i})">Delete</button></span></div></div>`}).join('')||'<p class="hint">No matching calculations.</p>'};

let audioCtx;
function clickSound(){if(localStorage.getItem('sound')!=='on')return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=620;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.045);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.05)}catch(e){}}
function pulseButton(e){let b=e.target.closest('button');if(!b)return;b.classList.remove('tap');void b.offsetWidth;b.classList.add('tap');clickSound()}
document.addEventListener('click',pulseButton,{passive:true});
if($('#sound'))$('#sound').onchange=e=>{save('sound',e.target.value);toast(e.target.value==='on'?'Sound enabled':'Sound disabled')};
function toggleFullscreen(){let el=document.documentElement;if(!document.fullscreenElement)el.requestFullscreen?.().then(()=>toast('Fullscreen enabled')).catch(()=>toast('Fullscreen unavailable'));else document.exitFullscreen?.()}
$('#fullscreenBtn')?.addEventListener('click',toggleFullscreen);
let deferredInstall=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;if($('#installBtn'))$('#installBtn').hidden=false});$('#installBtn')?.addEventListener('click',async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBtn').hidden=true});

/* Calculator edit feedback + undo snapshots */
$$('.keys button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.a!=='equal')pushUndo()}));
/* Keep splash progress synchronized with the visual bar and make the exit feel app-like. */
(()=>{const splash=$('#splash'),fill=$('#splashFill');if(!splash||!fill)return;const start=performance.now(),duration=4800;function frame(now){let p=Math.min(100,(now-start)/duration*100);fill.style.width=p+'%';if(p<100)requestAnimationFrame(frame);else setTimeout(()=>{splash.classList.add('is-exiting');setTimeout(()=>splash.classList.add('is-hidden'),850)},260)}requestAnimationFrame(frame)})();
renderHistory();
